version: '3'

services:
  db:
    image: mariadb:10.6-focal
    hostname: db
    restart: always
    env_file:
      - mariadb.env
    volumes:
      - ./datadir:/var/lib/mysql
    networks:
      - flasknet

  micro:
    depends_on:
      - db
    build: .
    image: flaskapi
    ports:
      - "5000:5000"
    restart: unless-stopped
    deploy:
      replicas: 1 # Solo puede haber 1 replica si se configura puertos.
    networks:
      - flasknet

networks:
  flasknet:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
